[2026-08-14] | [Phase 1] | Expo TypeScript project scaffold, design tokens, local SQLite schema, wardrobe grid, add-item modal, image picker, local image copy, and SQLite insert/list flow implemented | Build offline-first wardrobe foundation for local clothing registration and 3-column browsing
[2026-08-14] | [Phase 1] | Replaced optional expo-status-bar dependency with React Native StatusBar after npm ETARGET on expo-status-bar@~3.1.0 | Keep Phase 1 dependency set minimal and avoid a non-existent package version
[2026-08-14] | [Phase 1] | Added missing babel-preset-expo devDependency after Metro could not resolve the Expo Babel preset | Allow Expo Metro bundler to start with the standard Babel config
[2026-08-14] | [Phase 1] | Updated react-native and TypeScript package versions to Expo SDK compatibility check expectations | Keep the generated Expo app aligned with SDK-managed dependency versions
[2026-08-14] | [Phase 1] | Added Expo/Node project .gitignore entries | Keep generated dependencies and local bundler state out of source tracking
[2026-08-14] | [Phase 2] | Added bottom tab app shell for Wardrobe, CodiBook, and MyPage; added local outfits table and codi canvas screens | Separate closet browsing from outfit composition and prepare the app for styling workflows
[2026-08-14] | [Phase 2] | Added Expo image manipulation and slider dependencies plus local PNG compression pipeline in clothing registration | Start the on-device image processing path while keeping Expo emulator compatibility
[2026-08-14] | [Phase 2] | Implemented codi canvas sticker add, drag, resize, rotate, delete, layer-forward, reset, save, and restore flows | Let users compose saved outfits from locally stored wardrobe items without network access
[2026-08-14] | [Phase 3] | Applied LookBookie Supabase schema, RLS policies, and clothes storage bucket migration | Prepare cloud database and storage for authenticated wardrobe backups
[2026-08-14] | [Phase 3] | Added Supabase env setup, React Native client, auth helpers, and clothing cloud upload service | Connect local-first wardrobe registration to optional cloud sync
[2026-08-14] | [Phase 3] | Added owner_id indexes and optimized RLS policies after Supabase performance advisor warnings | Keep authenticated cloud queries scalable as wardrobe and outfit data grows
[2026-08-14] | [Phase 4] | Added Supabase profiles/friendships schema and friend wardrobe read policy | Enable online lookup of another account wardrobe after adding them as a friend
[2026-08-14] | [Phase 4] | Added JSON backup export/import services and MyPage controls using Expo DocumentPicker and Sharing | Let users back up and restore local wardrobe/outfit text data without image file embedding
[2026-08-14] | [Phase 4] | Added friend profile sync, friend add by email, friend list, and online friend wardrobe preview | Complete the first online sharing path while keeping the user's own wardrobe local-first
[2026-08-14] | [UX Fix] | Added SafeAreaProvider/inset-aware tab positioning and replaced core SafeAreaView imports | Fix safe area warnings and prevent top/bottom content clipping on emulator devices
[2026-08-14] | [UX Fix] | Changed image picker to select full images, added in-app crop modes, expanded representative color palette, and fixed unauthenticated sync status to pending | Reduce registration friction and avoid misleading failed cloud tags before login
[2026-08-14] | [Phase 2] | Added separate WebView canvas eraser editor with visible brush preview and transparent PNG export | Make background erasing a real manual alpha-editing step instead of a placeholder control
[2026-08-14] | [Phase 2] | Split CodiBook into library selection and canvas arrangement modes | Make outfit composition easier by separating item picking from drag/resize/rotate editing
[2026-08-14] | [Phase 2] | Rebuilt clothing registration into gallery/camera selection, separate crop screen, eraser screen, and metadata form flow | Reduce image-picking friction and keep compression automatic at final save
[2026-08-14] | [Phase 2] | Added eraser stroke history with Undo/Redo and stopped brush-size changes from reloading the canvas | Preserve manual transparent-background edits while adjusting brush size
[2026-08-14] | [UX Fix] | Switched CodiBook sticker dragging to Animated position updates with final state commit on release | Make canvas item movement track the finger more naturally
[2026-08-14] | [UX Fix] | Added One-piece category, persistent custom color palette tags, compact wardrobe category chips, and cancel confirmation for in-progress item registration | Match updated wardrobe metadata and navigation UX requirements
[2026-08-14] | [UX Fix] | Added wardrobe detail editing with clothing name, image re-editing, and metadata updates | Let users revise individual wardrobe items after registration
[2026-08-14] | [UX Fix] | Reworked wardrobe grid cards to contain images without cropping and show the brand below the image | Keep clothing photos visible and avoid overlay text covering items
[2026-08-14] | [Phase 2] | Improved codi sticker resizing with animated draft size updates and moved eraser brush-size preview onto the image canvas with larger brush range and icon controls | Make canvas editing and background erasing feel more direct
[2026-08-14] | [Phase 4] | Added a dedicated Friends tab, friend wardrobe/outfit views, cloud outfit sync on save, and Supabase policies for friend outfit reads | Move friend workflows out of MyPage and enable friend codi browsing
[2026-08-14] | [Phase 2] | Rebuilt crop screen with drag-to-position and zoom controls plus pixel-rect cropping | Let users choose the exact image area before background erasing
[2026-08-14] | [Phase 2] | Added transparent-pixel trimming when exporting erased images | Resize edited clothing images around the remaining non-transparent subject
[2026-08-14] | [UX Fix] | Added editable/deletable custom color palette UI, wardrobe search, cloud icon badges, clothing delete, and sync retry controls | Improve wardrobe management after initial item registration
[2026-08-14] | [Phase 2] | Reworked CodiBook to open on saved outfits and use a separate searchable/category-filtered item picker with selected-item tray | Make outfit viewing primary and defer wardrobe importing until adding/editing a codi
