[2026-08-15] | [Backup Image Restore] | Validated local image files during JSON import, restored missing files from HTTPS cloud URLs into app storage, remapped outfit sticker paths and imported clothing IDs, and added stale-path recovery for previously imported records | Keep wardrobe and outfit images usable after app data deletion without embedding image binaries in backups
[2026-08-15] | [Cloud Status Icons] | Replaced pending and local arrow/dot badges with Lucide CloudAlert while retaining CloudCheck only for verified synced records | Make every pre-sync or failed state visually consistent with the requested cloud status language
[2026-08-15] | [Kakao Production Release] | Rebuilt the signed 1.1.0 (2) release APK with the production Kakao Native App Key, verified the release package and SHA-1 certificate, installed it as an update, and confirmed a successful Kakao ID-token exchange in Supabase Auth logs | Resolve the mismatch between the release Android registration and the development Kakao app key while preserving on-device data
[2026-08-15] | [Social Login UI Fix] | Narrowed the temporary Apple-login JSX comment to the Apple action only, rebuilt and reinstalled the signed local release APK, and verified Google and Kakao actions in the physical-device UI hierarchy | Restore the configured Android social login options that were unintentionally hidden with Apple
[2026-08-15] | [Local Release Build] | Canceled the stale cloud build after the icon changed, regenerated the production Android project, signed a local 1.1.0 (2) release APK with the existing release keystore, verified its package/version/certificate, and installed it as an update on the SM-S948N | Include the final launcher artwork while preserving the installed app identity and on-device data
[2026-08-15] | [Release Versioning] | Bumped the app to version 1.1.0 with Android versionCode 2 and changed EAS to use the locally declared version | Make the new APK install as an update over the existing 1.0.0 release and keep the effective build number reviewable before building
[2026-08-15] | [Apple Auth Temporary Disable] | Hid the Apple login action while retaining its implementation for later iOS release setup | Keep the current Android release focused on fully configured Google, Kakao, and email authentication
[2026-08-15] | [Direct JSON Backup] | Replaced the Android share-sheet export with Storage Access Framework folder selection and direct JSON file creation | Let users download backups to a chosen device folder without routing through sharing apps
[2026-08-15] | [Authentication Provider Display] | Persisted the successful sign-in method per account and preferred linked social identities over the primary email identity when deriving the account label | Show Google and Kakao sessions accurately even when Supabase reports email as the primary provider
[2026-08-15] | [Unified App Dialogs] | Replaced all 65 Android-native Alert calls with a queued LookBoogie design dialog, centralized turtle header and primary/cancel/destructive actions, and moved existing confirmation dialogs onto the same shared surface | Keep validation, errors, confirmations, and destructive actions visually consistent across Android while preserving their existing callbacks
[2026-08-15] | [Account Deletion] | Added a JWT-protected Supabase Edge Function and custom My Page confirmation flow that delete the user's Storage objects, Auth account, cascaded cloud wardrobe/outfit/friend records, and provider sessions while retaining local wardrobe and outfit data as offline-only records | Provide a complete irreversible account deletion path without discarding the user's on-device collection
[2026-08-15] | [Splash Timing] | Reduced the enforced branded splash duration from two seconds to 1.5 seconds | Keep the revised launch artwork visible while shortening startup delay
[2026-08-15] | [Branded Device Rebuild] | Regenerated Android native resources from the revised icon and splash artwork, visually inspected the packaged density assets, built a signed debug APK, and installed and launched it on the SM-S948N | Ensure the latest brand artwork and two-second splash behavior are present in the custom development client
[2026-08-15] | [Clipboard Device Build] | Compiled and installed a new SM-S948N development APK with Expo Clipboard autolinked alongside the existing Google and Kakao native modules | Make the friend-search ID Copy control executable in the custom development client
[2026-08-15] | [Friend ID Copy] | Added an Expo Clipboard-backed Copy icon beside the account page friend-search ID with temporary checked feedback and accessible state labels | Let users share their exact LookBoogie ID without transcription errors
[2026-08-15] | [MyPage Information Architecture] | Replaced the inline cloud panel with separate Account and LookBoogie Sync settings pages, added a turtle profile summary and custom ID/nickname editor modal, and consolidated cloud sync with local JSON backup controls | Keep the main profile screen scannable while separating identity management from data synchronization workflows
[2026-08-15] | [Friend List Search] | Added instant local friend-list filtering by friend-facing nickname or editable LookBoogie ID with a clear action and distinct no-result state | Keep longer friend lists easy to navigate without adding network dependency or conflating profile IDs with display names
[2026-08-15] | [Profile Identity UX] | Replaced friend-code lookup with editable unique LookBoogie IDs and changed the My Page account line from email to the active Google, Kakao, Apple, or email login method | Make friend discovery memorable and show users which authentication method owns the current cloud session
[2026-08-15] | [Editable LookBoogie IDs] | Added a follow-up migration that replaces immutable friend codes with case-insensitive unique profile handles that owners can edit | Provide memorable user-controlled IDs for friend discovery while retaining UUID primary keys for database relationships
[2026-08-15] | [Email-less Kakao App Flow] | Removed the client-side Kakao email rejection, separated signed-in state from email display, created nickname-based Kakao labels, and changed friend lookup to accept immutable friend codes or email | Let non-Biz Kakao users keep valid Supabase sessions and use cloud/friend features without pretending they are anonymous guests
[2026-08-15] | [Email-less Kakao Profiles] | Added a Supabase migration that makes profile email optional and assigns immutable UUID-derived friend codes | Support Kakao accounts without Biz App email consent while keeping friend discovery independent from provider email
[2026-08-15] | [Native Kakao Auth Diagnostics] | Added privacy-safe stage, issuer, audience-match, nonce-presence, email-verification, and Supabase error-code logging for Kakao sign-in failures | Distinguish Kakao SDK failures from Supabase token-exchange failures without recording ID tokens or account email addresses
[2026-08-15] | [Native Kakao Auth] | Mapped Supabase's unverified Kakao email rejection to a concise Korean account-verification instruction | Help users resolve a provider-account verification issue without exposing raw backend messages or weakening email trust checks
[2026-08-15] | [Native Kakao Device Debug] | Generated a side-by-side `com.lookboogie.app.debug` project from environment-aware Expo config, built and installed it on the connected SM-S948N, restarted Metro with the Kakao environment, and verified startup without native or JavaScript crashes | Validate the native Kakao build on a physical device without replacing the release app or its local data
[2026-08-15] | [Local Android Workflow] | Added persistent development-package scripts and ignored generated Android/iOS directories | Preserve the `룩부기 Dev` package across Expo prebuilds and keep generated native output out of source control
[2026-08-15] | [Native Kakao Setup] | Separated development and production Native App Keys in the Kakao setup guide and listed both audiences for Supabase validation | Match Kakao Developers' key-scoped Android package registration while keeping debug and release builds usable
[2026-08-15] | [Native Kakao Build] | Verified Expo prebuild output for the Kakao app-key resource, OAuth callback activity, Maven repository, and completed an Android debug APK compilation with Java 21 | Confirm the selected Kakao SDK and config plugin compile against the current Expo and React Native versions before device testing
[2026-08-15] | [Native Kakao Auth] | Replaced Kakao browser OAuth with KakaoTalk-first native login, shared SHA-256 nonce validation, Supabase ID-token exchange, native logout, and provider-specific error handling | Provide the requested app-native Kakao experience while preserving replay protection and the existing Supabase session model
[2026-08-15] | [Native Kakao Setup] | Added the Kakao native SDK, Expo config plugins, Kakao Maven repository, environment template, Android package/key-hash instructions, and native audience configuration guidance | Make development and release builds reproducible across Kakao Developers and Supabase settings
[2026-08-15] | [Native Google Auth] | Added per-attempt cryptographic nonce generation, passed the SHA-256 nonce to Google Credential Manager, and supplied the raw nonce to Supabase ID-token exchange | Resolve nonce-presence validation failures while retaining replay protection for native Google sign-in
[2026-08-15] | [Native Google Auth] | Mapped Android Credential Manager error 28444 to a concise configuration message and documented the side-by-side debug package SHA-1 | Prevent native stack traces from reaching users and make physical-device OAuth setup reproducible
[2026-08-15] | [Native Device Debug] | Built and installed a side-by-side `com.lookboogie.app.debug` Android app on the connected SM-S948N, configured USB Metro forwarding, and verified the rendered wardrobe without runtime errors | Test native modules and Google authentication on a physical phone without replacing the EAS-signed app or deleting its local data
[2026-08-15] | [Native Google Auth] | Replaced Google browser OAuth with Android Credential Manager and iOS Google Sign-In ID Token exchange through Supabase, including native Google logout and environment-driven iOS config | Provide the requested app-native account experience while retaining Expo development builds and the existing Supabase session model
[2026-08-15] | [Native Google Build] | Added the Nitro Google Sign-In native modules and verified Android autolinking, Kotlin/Java/C++ compilation, and packaged native libraries with Java 21 | Confirm the modern Google authentication SDK is present in a real APK before provider credentials are configured
[2026-08-15] | [Social Authentication] | Added Google, Kakao, and Apple Supabase OAuth with Expo browser-session callbacks, provider-specific MyPage controls, and mobile deep-link configuration | Let users authenticate with social accounts while preserving the existing persistent Supabase session and offline-first app flow
[2026-08-15] | [Social Authentication Setup] | Documented the LookBoogie Supabase callback, mobile redirect allow-list, and provider-console requirements for Google, Kakao, and Apple | Keep provider secrets out of the client and make the remaining dashboard setup reproducible
[2026-08-15] | [Release Build] | Built and signature-verified a new Android preview APK from the revised `icon.png`, then extracted the packaged high-density launcher icon for visual confirmation | Ensure the installable build uses the latest 룩부기 icon artwork rather than a cached native asset
[2026-08-15] | [Release Build] | Rebuilt and signature-verified the Android preview APK with the managed 2-second native splash hold | Provide an installable artifact that reflects the latest launch timing behavior
[2026-08-15] | [Splash Timing] | Prevented automatic splash dismissal and added a managed 2-second native splash hold before revealing the application | Keep the supplied 룩부기 launch artwork visible long enough to be recognized consistently
[2026-08-15] | [Release Build] | Produced and signature-verified a branded Android preview APK with the supplied launcher icon and native splash assets | Verify Expo native asset generation in an installable release artifact
[2026-08-15] | [Brand Assets] | Configured `icon.png` as the 룩부기 application icon and `splash.png` as a centered native splash image through the Expo splash-screen plugin | Apply the supplied visual identity consistently to native app launches and installed icons
[2026-08-15] | [Navigation UX] | Added friend-detail hardware/header back navigation, removed the mascot from CodiBook creation, and redesigned the edge-attached bottom navigation with compact active icon wells | Make nested navigation predictable and the primary navigation visually quieter
[2026-08-15] | [Wardrobe Organization] | Added name/newest/oldest sorting plus multi-select season and palette-color filters to the wardrobe | Keep larger wardrobes scannable without changing offline-first storage behavior
[2026-08-15] | [Personalization] | Moved category and color editing behind MyPage settings rows, made color editors open beside their selected row, and added long-press drag ordering persisted in local preferences | Reduce MyPage clutter and let users control category and palette presentation order
[2026-08-15] | [Friend Profiles] | Added a verified Supabase display-name editor, preserved existing names during profile initialization, and replaced friend initials with Lucide turtle avatars | Give users a stable friend-facing identity and consistent profile visuals
[2026-08-15] | [Branding] | Changed the Expo application display name to 룩부기 | Show the Korean product name on installed devices
[2026-08-15] | [Release Build] | Produced and signature-verified the Android preview APK for LookBoogie 1.0.0 (`com.lookboogie.app`) | Provide an installable device build containing the latest UX, friend browsing, and outfit sync fixes
[2026-08-15] | [UX Polish] | Attached the bottom navigation to the screen edges, fixed category and selected-item clipping, added keyboard-aware form space, pull-to-refresh, card image insets, custom cancel dialog, and icon-based action controls | Resolve APK usability issues across long lists, forms, wardrobe cards, outfit selection, and canvas handles
[2026-08-15] | [Personalization] | Added MyPage category management and editable color palettes with an HSV color picker; simplified built-in item color choices to swatches and corrected suggested-color selection styling | Let users maintain searchable categories and colors without manual hex-only input
[2026-08-15] | [Friends UX] | Split the friend list from friend detail and matched friend wardrobe/CodiBook search, category filters, three-column cards, outfit previews, and pull-to-refresh to the owner's screens | Make browsing shared wardrobes consistent with personal wardrobe workflows
[2026-08-15] | [Cloud Sync] | Added local remote IDs and cloud states for outfits, changed cloud saves to verified insert/update behavior, added verified remote deletion, and limited legacy duplicate cleanup to uniquely named local outfits | Prevent repeated outfit inserts and keep SQLite and Supabase CodiBook records aligned
[2026-08-14] | [Phase 1] | Expo TypeScript project scaffold, design tokens, local SQLite schema, wardrobe grid, add-item modal, image picker, local image copy, and SQLite insert/list flow implemented | Build offline-first wardrobe foundation for local clothing registration and 3-column browsing
[2026-08-14] | [Phase 1] | Replaced optional expo-status-bar dependency with React Native StatusBar after npm ETARGET on expo-status-bar@~3.1.0 | Keep Phase 1 dependency set minimal and avoid a non-existent package version
[2026-08-14] | [Phase 1] | Added missing babel-preset-expo devDependency after Metro could not resolve the Expo Babel preset | Allow Expo Metro bundler to start with the standard Babel config
[2026-08-14] | [Phase 1] | Updated react-native and TypeScript package versions to Expo SDK compatibility check expectations | Keep the generated Expo app aligned with SDK-managed dependency versions
[2026-08-14] | [Phase 1] | Added Expo/Node project .gitignore entries | Keep generated dependencies and local bundler state out of source tracking
[2026-08-14] | [Phase 2] | Added bottom tab app shell for Wardrobe, CodiBook, and MyPage; added local outfits table and codi canvas screens | Separate closet browsing from outfit composition and prepare the app for styling workflows
[2026-08-14] | [Phase 2] | Added Expo image manipulation and slider dependencies plus local PNG compression pipeline in clothing registration | Start the on-device image processing path while keeping Expo emulator compatibility
[2026-08-14] | [Phase 2] | Implemented codi canvas sticker add, drag, resize, rotate, delete, layer-forward, reset, save, and restore flows | Let users compose saved outfits from locally stored wardrobe items without network access
[2026-08-14] | [Phase 3] | Applied LookBoogie Supabase schema, RLS policies, and clothes storage bucket migration | Prepare cloud database and storage for authenticated wardrobe backups
[2026-08-14] | [Phase 3] | Added Supabase env setup, React Native client, auth helpers, and clothing cloud upload service | Connect local-first wardrobe registration to optional cloud sync
[2026-08-14] | [Phase 3] | Added owner_id indexes and optimized RLS policies after Supabase performance advisor warnings | Keep authenticated cloud queries scalable as wardrobe and outfit data grows
[2026-08-14] | [Phase 4] | Added Supabase profiles/friendships schema and friend wardrobe read policy | Enable online lookup of another account wardrobe after adding them as a friend
[2026-08-14] | [Phase 4] | Added JSON backup export/import services and MyPage controls using Expo DocumentPicker and Sharing | Let users back up and restore local wardrobe/outfit text data without image file embedding
[2026-08-14] | [Phase 4] | Added friend profile sync, friend add by email, friend list, and online friend wardrobe preview | Complete the first online sharing path while keeping the user's own wardrobe local-first
[2026-08-14] | [UX Fix] | Added SafeAreaProvider/inset-aware tab positioning and replaced core SafeAreaView imports | Fix safe area warnings and prevent top/bottom content clipping on emulator devices
[2026-08-14] | [UX Fix] | Changed image picker to select full images, added in-app crop modes, expanded representative color palette, and fixed unauthenticated sync status to pending | Reduce registration friction and avoid misleading failed cloud tags before login
[2026-08-14] | [Phase 2] | Added separate WebView canvas eraser editor with visible brush preview and transparent PNG export | Make background erasing a real manual alpha-editing step instead of a placeholder control
[2026-08-14] | [Phase 2] | Split CodiBook into library selection and canvas arrangement modes | Make outfit composition easier by separating item picking from drag/resize/rotate editing
[2026-08-14] | [Phase 2] | Rebuilt clothing registration into gallery/camera selection, separate crop screen, eraser screen, and metadata form flow | Reduce image-picking friction and keep compression automatic at final save
[2026-08-14] | [Phase 2] | Added eraser stroke history with Undo/Redo and stopped brush-size changes from reloading the canvas | Preserve manual transparent-background edits while adjusting brush size
[2026-08-14] | [UX Fix] | Switched CodiBook sticker dragging to Animated position updates with final state commit on release | Make canvas item movement track the finger more naturally
[2026-08-14] | [UX Fix] | Added One-piece category, persistent custom color palette tags, compact wardrobe category chips, and cancel confirmation for in-progress item registration | Match updated wardrobe metadata and navigation UX requirements
[2026-08-14] | [UX Fix] | Added wardrobe detail editing with clothing name, image re-editing, and metadata updates | Let users revise individual wardrobe items after registration
[2026-08-14] | [UX Fix] | Reworked wardrobe grid cards to contain images without cropping and show the brand below the image | Keep clothing photos visible and avoid overlay text covering items
[2026-08-14] | [Phase 2] | Improved codi sticker resizing with animated draft size updates and moved eraser brush-size preview onto the image canvas with larger brush range and icon controls | Make canvas editing and background erasing feel more direct
[2026-08-14] | [Phase 4] | Added a dedicated Friends tab, friend wardrobe/outfit views, cloud outfit sync on save, and Supabase policies for friend outfit reads | Move friend workflows out of MyPage and enable friend codi browsing
[2026-08-14] | [Phase 2] | Rebuilt crop screen with drag-to-position and zoom controls plus pixel-rect cropping | Let users choose the exact image area before background erasing
[2026-08-14] | [Phase 2] | Added transparent-pixel trimming when exporting erased images | Resize edited clothing images around the remaining non-transparent subject
[2026-08-14] | [UX Fix] | Added editable/deletable custom color palette UI, wardrobe search, cloud icon badges, clothing delete, and sync retry controls | Improve wardrobe management after initial item registration
[2026-08-14] | [Phase 2] | Reworked CodiBook to open on saved outfits and use a separate searchable/category-filtered item picker with selected-item tray | Make outfit viewing primary and defer wardrobe importing until adding/editing a codi
[2026-08-14] | [Phase 2] | Added CodiBook hardware/header back-to-list behavior and saved-layout outfit preview cards | Keep CodiBook browsing aligned with the user's saved sticker arrangement
[2026-08-14] | [Phase 2] | Added pinch-to-zoom crop gestures and representative color extraction through a hidden WebView canvas sampler | Make image editing more direct and reduce manual color entry
[2026-08-14] | [UX Fix] | Expanded color palette data to include HEX values and searchable color families with editable custom family selection | Support color-family search such as red matching red-adjacent wardrobe items
[2026-08-14] | [Phase 4] | Reworked friends into pending requests, incoming accept/decline UX, and accepted-only wardrobe/outfit read policies | Require consent before another account can browse shared wardrobe data
[2026-08-14] | [UX Fix] | Collapsed manual color palettes behind the automatic recommendation until the user asks to pick another color | Keep the metadata form focused after representative color extraction
[2026-08-14] | [Phase 2] | Removed CodiBook sticker borders and added codi name plus season chips to the canvas editor and saved outfit cards | Let users save clearer codi metadata without visual frames around placed clothes
[2026-08-14] | [Phase 3] | Added local and Supabase outfit seasons storage with a database migration and friend outfit read mapping | Keep codi season metadata available offline and in shared friend outfit views
[2026-08-14] | [UX Fix] | Replaced CodiBook detail back controls with header save/delete actions, unified wardrobe/codi add FABs, and added alpha-shaped selected sticker outlines | Clarify which clothing item is being edited while keeping add actions consistent
[2026-08-14] | [UX Fix] | Moved CodiBook delete, rotate, and resize handles to the visible image bounds with a minimum handle spacing fallback | Attach sticker tools to the clothing image instead of transparent square padding
[2026-08-14] | [UX Fix] | Added CodiBook list search across codi name, season, and included wardrobe item metadata | Let users find saved outfits by styling context and clothing details
[2026-08-14] | [Branding] | Installed Lucide SVG icon support, converted bottom tabs to vector icons, and renamed app branding to LookBoogie/룩부기 | Modernize icon rendering and align product naming with the new brand
[2026-08-14] | [UX Fix] | Replaced wardrobe cloud sync text badges with Lucide CloudCheck and CloudAlert icons | Make cloud sync states visually consistent with the new vector icon system
[2026-08-14] | [UX Fix] | Renamed wardrobe and codi headers to 룩부기 옷장/룩부기 코디북 and wired turtle header buttons to refresh local data | Make top navigation branding consistent and give users an obvious reload affordance
[2026-08-14] | [UX Fix] | Matched the CodiBook header turtle button size to the Wardrobe header turtle button | Keep LookBoogie header controls visually consistent across tabs
[2026-08-14] | [Bug Fix] | Switched backup import to Expo FileSystem file picker with a legacy read fallback and clearer permission error messaging | Avoid File.text read-permission failures when importing JSON backups from external file locations
[2026-08-14] | [Phase 4 Fix] | Invalidated restored cloud-sync checks until verification, added remote-row reconciliation, and recreated missing cloud records during retry sync | Prevent backup metadata from claiming a deleted Supabase row is still synced
[2026-08-14] | [Release Setup] | Added EAS preview APK and production Android App Bundle build profiles | Enable direct Android test installation now while preserving a separate Play Store build path
[2026-08-14] | [Release Build] | Linked the existing EAS project, uploaded preview Supabase variables, generated Android signing credentials, and produced a verified local preview APK | Deliver an installable LookBoogie Android build while the matching cloud build runs
